### ISSUE TITLE
error in docs

### ISSUE THREAD

**Issue by it-can** [BabDev/laravel-server-push-manager#4]
Hi,

there is a little error in your docs https://www.babdev.com/open-source/packages/laravel-server-push-manager/docs/2.x/usage

```
'as' => 'stylesheet'
```

should be:

```
'as' => 'style'
```

**Comment by mbabker** [comment]
All of the package docs are contained in their respective repos, so you can send a PR updating https://github.com/BabDev/laravel-server-push-manager/blob/2.x/docs/usage.md or I'll get around to it at some point over the weekend.

**Comment by it-can** [comment]
created a PR... thanks for this package 👍🏻
